paradify.net/pcore/pcore/pcore.web/Controllers/AuthorizeController.cs

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using pcore.web;
using web.Services;

namespace web.Controllers
{
    public class AuthorizeController : Controller
    {
        public readonly AppSettings Settings;
        private readonly ISessionService _sessionService;
        public readonly ITokenCookieService _tokenCookieService;
        public AuthorizeController(ISessionService sessionService, ITokenCookieService tokenCookieService, IOptions<AppSettings> settings)
        {
            _sessionService = sessionService;
            _tokenCookieService = tokenCookieService;
            Settings = settings.Value;
        }



        public ActionResult Index(string url, bool? fromIFrame)
        {
            if (fromIFrame.HasValue && fromIFrame.Value)
            {
                _sessionService.SetBoolean("fromIframe", fromIFrame.Value);
            }

            if (!string.IsNullOrEmpty(url))
                _sessionService.SetReturnUrl(url);
            else
                if (Request.Headers["Referer"].ToString() != null)
                _sessionService.SetReturnUrl(Request.Headers["Referer"].ToString());

            return
                Redirect(
                    string.Format(Settings.AuthorizeUrlFormat,
                    Settings.ClientId, System.Net.WebUtility.UrlEncode(Settings.RedirectUri), Settings.Scope, Settings.StateKey)
                    );
        }

        public ActionResult Logout()
        {
            _tokenCookieService.Signout();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult CloseIframe()
        {
            return View();
        }
    }
}

paradify.net/pcore/pcore/pcore.web/Controllers/SearchPController.cs
using SpotifyAPI.Web.Models;
using web.Services;
using web.Filters;
using web.Models;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using pcore.web;
using Microsoft.Extensions.Options;

namespace web.Controllers
{

    public class SearchPController : CustomControllerBase
    {
        private readonly IParadifyService _paradifyService;
        private readonly ITokenCookieService _tokenCookieService;
        private readonly IUserService _userService;
        private readonly ISessionService _sessionService;
        private readonly IPlaylistService _playlistService;
        private readonly AppSettings Settings;

        public string _search { get; set; }
        public string _trackId { get; set; }

        public SearchPController(IParadifyService paradifyService, ITokenCookieService tokenCookieService,
            IUserService userService, ISessionService sessionService, IPlaylistService playlistService,
            IOptions<AppSettings> settings)
            : base(paradifyService, tokenCookieService,
             userService, playlistService)
        {
            _paradifyService = paradifyService;
            _tokenCookieService = tokenCookieService;
            _userService = userService;
            _sessionService = sessionService;
            _playlistService = playlistService;
            Settings = settings.Value;
        }

        [ServiceFilter(typeof(FilterClientToken))]
        public ActionResult Index(string q)
        {
            _search = q;
            _trackId = "";

            SearchResult searchResult = new SearchResult();

            if (!_search.NullCheck())
            {
                _search = _search.Decode();

                ViewBag.Title = string.Format("{0} - {1}", _search, Settings.SingleTitle);

                CustomToken token = ViewBag.Token;
                SearchItem searchItem = null;
                if (!token.IsTokenEmpty())
                {
                    searchItem = Search(_search, token);

                    if (searchItem != null && searchItem.Tracks != null &&
                        searchItem.Tracks.Items != null && searchItem.Tracks.Items.Count == 0)
                    {
                        var tempSearch = Regex.Replace(_search, "\\([^\\]]*\\)", "");
                        searchItem = Search(tempSearch, token);
                    }
                }
                else
                {
                    searchResult.IsTokenEmpty = true;
                }

                searchResult.SearchItem = searchItem;
                searchResult.query = _search;
                searchResult.track = _trackId;
            }

            return View("Index", searchResult);
        }

        private SearchItem Search(string query, Token token)
        {
            return _paradifyService.SearchResult(query, token, 35);
        }

        private void SetSearchReturnUrl(string search)
        {
            var returnUrl = Helper.SetSearchReturnUrl(RouteData.Values["controller"].ToString(), search);

            _sessionService.SetReturnUrl(returnUrl);
        }
    }
}

paradify.net/pcore/pcore/pcore.web/Views/Shared/_Countries.cshtml
@using web.Models
@model List<Country>
<div class="form-group" id="select-countries">
    <select class="custom-select col-lg-4">
        <option selected="">Country</option>
        @foreach (var item in Model)
        {
            <option value="@item.Code">@item.Name</option>
        }
    </select>
    <script>
        function selectCountry(countryCode) {
            $('.custom-select').val(countryCode);
        }

        function initCountries() {
            $('.custom-select').change(function () {
                country_Onchanged($('#select-countries option:selected').val());
            });
        }
    </script>
</div>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top header">
    <a class="navbar-brand" href="~/"><img src="~/src/web/images/head-logo.png" class="logo" /></a>
    <a class="nav-link" href="~/">Paradify</a>
    <script>populateOpenInWeb();</script>
    @using (Html.BeginForm("Index", "SearchP", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
    {
        <i class="fa fa-search"></i><input id="q" name="q" class="form-control mr-sm-2  is-valid custom-search" autocomplete="off" type="text" placeholder="search song" value="@(Context.Request.Query["q"])"> @*<button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>*@
    }
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            </li>
        </ul>
        <span class="">
            <a class="nav-item active custom-li-me" id="profile_login"></a>
        </span>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_Intro.cshtml
<div class="col-lg-6 intro" style="margin-top:20px; margin:auto;">
    <h4>Youtube to Spotify</h4>
    <p>
        <div>1 - Play something on Youtube (or on other supported web sites)</div>
        <div>2 - Click Paradify extension</div>
        <div>3 - It's done</div>
    </p>

    <p>
        <strong>Supported web sites</strong>
        <ul class="ul-supported-web-sites">
            <li><a href="https://www.youtube.com/watch?v=YQHsXMglC9A" target="_blank">YouTube</a></li>
            <li><a href="http://www.jango.com/music/Jay+Z" target="_blank">Jango</a></li>
            <li><a href="https://tunein.com/radio/Radio-Veronica-80s-Hits-s242550/" target="_blank">Tune in(many radios are in)</a></li>
            <li><a href="https://www.dailymotion.com/video/x3e1r8n" target="_blank">Daily Motion</a></li>
            <li><a href="https://vimeo.com/150178241" target="_blank">Vimeo</a></li>
            <li><a href="https://soundcloud.com/johnnycash/hurt-album-version" target="_blank">Sound Cloud</a></li>
            <li><a href="https://www.deezer.com/en/channels/rap" target="_blank">Deezer</a></li>
            <li><a href="http://www.radioparadise.com/rp_2.php?#" target="_blank">Radio Paradise</a></li>
            <li><a href="https://qmusic.nl/" target="_blank">Q Music</a></li>
            <li><a href="http://www.radioswissjazz.ch/en" target="_blank">Radio Swiss Jazz</a></li>
            <li><a href="http://www.powerapp.com.tr/powerfm" target="_blank">Power Fm(many radios are in)</a></li>
            <li>Kral Fm</li>
            <li><a href="https://karnaval.com/" target="_blank">Karnaval(many radios are in)</a></li>
            <li><a href="https://open.spotify.com/album/4E2eUhFHqTG2pu9MN1NDIF" target="_blank">Spotify Web</a></li>
            <li><a href="https://www.beatport.com/track/only-human-original-mix/11639590" target="_blank">Beatport DJ & Dance Music</a></li>
        </ul>
    </p>
</div>

<div class="col-lg-6  intro" style="margin-top:20px">
    <div class="custom-bottom">
        <h4>What do you need to do?</h4>
        <p>
            1. <a href="https://chrome.google.com/webstore/detail/paradify-youtube-radios-t/bocdilfmhiggklhdifohjfghbdncgele" onclick="chromeStoreClick()" target="_blank">
            install
            </a> Paradify Chrome Extension

        </p>

        <p>
            2. if you don't feel installing, just search up there
        </p>
    </div>

    <h6>Why you should donate?</h6>
    <p>
        First of all, you don't have to... But, Paradify needs to be hosted on a cloud server and be paid. Your tiny help will keep Paradify live. Please feel free to change the amount to whatever you would like.
        <br/>
        <a href="https://www.paypal.me/volkanakinpasa/5" target="_blank">Paypal me 5€ </a>
    </p>

    <h4>Say something</h4>
    <p>
        Don't be shy! Just drop a message
        <a href="@Url.Action("Contact", "Home")">here</a>
    </p>
</div>
<script>

    function install() {
        chrome.webstore.install('https://chrome.google.com/webstore/detail/bocdilfmhiggklhdifohjfghbdncgele', function () {

        }, function (err) {
        });
    }
</script>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_Login.cshtml
@using SpotifyAPI.Web.Models
@model PrivateProfile
<div class="nav-item dropdown">
@if (Model == null || string.IsNullOrEmpty(Model.Id))
{
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="fa fa-user" style="font-size:20px;"></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    @(Html.ActionLink("Login", "Index", "Authorize", null, new { id = "loginLink", @class = "dropdown-item" }))
    </div>
}
else
{
    var firstImage = Model.Images.FirstOrDefault();

    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    @if (firstImage != null)
    {
        <span>@(Model.DisplayName != null ? Model.DisplayName : Model.Id)</span>
        <img id="profile_pic" class="profile_pic" src="@firstImage.Url" />
    }
    else
    {
        <span class="fa fa-user" style="font-size:20px;"></span>
    }
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    @(Html.ActionLink("Logout", "Logout", "Authorize", null, new { @class = "dropdown-item" }))
    </div>
}
</div>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_LoginMessage.cshtml
<p style="text-align:center;">
    <button type="button" class="btn btn-success custom-link-login-popup"
            onclick="redirectToLogin('@Url.Action("Index", "Authorize", new { fromIFrame = true })')">
        Login on Spotify
    </button>
    <button type="button" class="btn btn-success custom-link-login"
            onclick="javascript:location.href = '@(Url.Action("Index", "Authorize"))'">
        Login on Spotify
    </button>

</p>
<p style="color:green">
    Parafiy does <b>NOT</b> keep any username or password, you will be redirected to Spotify login page
</p>
<script>
    populateLoginLinks();
    gaEvent.track.selectedToAddPlaylistButLoging();
</script>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_NewReleasedTracks.cshtml
@using SpotifyAPI.Web.Models
@using web.Models;
@using System.Web
@model CustomSimpleTrack

@if (Model != null && Model.Paging != null && Model.Paging.Items != null)
{
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col"><button title="Add all songs to playlist" type="button" class="btn btn-success" onclick="selectAll('@string.Join(",", Model.Paging.Items.Select(t => t.Id))')"> + </button></th>
            <th scope="col">Title - Artist - Album</th>
            <th scope="col" style="width: 116px;text-align: right;">Recommend</th>
        </tr>
    </thead>
    <tbody>
        @foreach (SimpleTrack item in Model.Paging.Items)
        {
            var track = item;
            var album = Model.TrackAlbumIds.FirstOrDefault(a => a.Key == item.Id);
            <tr>
                <td scope="row" style="width:47px;">
                    @if(@track.PreviewUrl !=null && @track.PreviewUrl.Length > 0) { 
                        <div class="number-playback-pic" playback="@track.PreviewUrl"  trackName="@HttpUtility.JavaScriptStringEncode(track.Name)">
                            <span class="player">
                                <span class="play-pause"></span>
                            </span>
                            @if (album.Value.Images.Count > 0)
                            {
                                <img class="track-image" src="@album.Value.Images[0].Url" preview-url="@track.PreviewUrl" />
                            }
                            else
                            {
                                <img class="track-image" src="~/src/web/images/head-logo.png" preview-url="@track.PreviewUrl" />
                            }
                        </div>
                    }
                </td>
                <td style="width:54px;">
                    <button title="Add to playlist" type="button" class="btn btn-success" onclick="javascript:select('@track.Id', '@HttpUtility.JavaScriptStringEncode(track.Name)', '@track.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)');"> + </button>

                </td>
                @{ 
                    var artistNames = string.Join(" - ", track.Artists.Select(a => a.Name));
                    var trackNameArtistNames = string.Format("{0} - {1}", track.Name, artistNames);
                }
                
                <td><span class="trackName">@Html.RouteLink(track.Name, "Search", new { q = trackNameArtistNames }, new { title = trackNameArtistNames })</span> -
                <span class="artistName">@artistNames</span> -
                <span>@album.Value.Name</span></td>
               
                <td style="text-align:right">
                    <button type="button" class="btn btn-info" onclick="javascript:recommend('@track.Id', '@HttpUtility.JavaScriptStringEncode(track.Name)', '@track.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)');"> R </button>
                </td>
            </tr>

        }
    </tbody>
</table> 
}

paradify.net/pcore/pcore/pcore.web/Views/Shared/_PlaylistList.cshtml
@using SpotifyAPI.Web.Models
@model List<SimplePlaylist>
<p>Select a playlist</p>
<div class="list-group">
    @foreach (SimplePlaylist playlist in Model)
    {
        <span class="list-group-item list-group-item-action custom-list-group-item-playlist">
            @*@if (playlist.Images != null && playlist.Images.Count > 0)
            {
            <img src="@playlist.Images[0].Url">
            }*@
            <button type="button" class="btn btn-success" onclick="javascript:addToPlaylist('@(playlist.Id)')"> + </button>
            <a href="javascript:addToPlaylist('@(playlist.Id)')"
               data-toggle="tooltip" data-placement="top" title="" data-original-title="Tooltip on top">
                @(playlist.Name)
                <span>(@(playlist.Tracks != null ? playlist.Tracks.Total.ToString() : "0" ))</span>
            </a>
        </span>
    }
</div>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_RecentlyPlayedTracks.cshtml
@using SpotifyAPI.Web.Models
@using System.Web
@model CursorPaging<PlayHistory>
@if (Model != null && Model.Items != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Artist</th>

                <th scope="col">Time</th>
                <th scope="col" style="width: 116px;text-align: right;">Recommend New Tracks</th>
            </tr>
        </thead>
        <tbody>
            @foreach (PlayHistory history in Model.Items)
            {
                var track = history.Track;

                <tr>
                    <td scope="row" style="width:47px;">
                        <div class="number-playback-pic" playback="@track.PreviewUrl" trackName="@HttpUtility.JavaScriptStringEncode(track.Name)">
                            <span class="player">
                                <span class="play-pause"></span>
                            </span>

                            <img class="track-image" src="~/src/web/images/head-logo.png" preview-url="@track.PreviewUrl" />

                        </div>
                    </td>
                    <td style="width:54px;">
                        <button type="button" class="btn btn-success" onclick="javascript:select('@track.Id', '@HttpUtility.JavaScriptStringEncode(track.Name)', '@track.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)', false, false, true);"> + </button>

                    </td>
                    <td><span class="trackName">@Html.RouteLink(track.Name, "Search", new { q = track.Name }, new { title = track.Name })</span></td>
                    <td><span class="artistName">@string.Join(" - ", track.Artists.Select(a => a.Name))</span></td>

                    <td>

                        @{
                            TimeSpan t = TimeSpan.FromMilliseconds(track.DurationMs);
                            string time = string.Format("{0:D2}:{1:D2}",
                            t.Minutes,
                            t.Seconds
                            );
                        }
                        @time

                    </td>
                    <td style="text-align:right">
                        <button type="button" class="btn btn-info" onclick="javascript:recommend('@track.Id', '@HttpUtility.JavaScriptStringEncode(track.Name)', '@track.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)');"> R </button>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}

paradify.net/pcore/pcore/pcore.web/Views/Shared/_RecommendedSongListShort.cshtml
@using SpotifyAPI.Web.Models
@using System.Web
@model List<FullTrack>

@if (Model != null)
{
    <ul class="ulSongList-reco">
        @foreach (FullTrack track in Model)
        {
        <li track-id="@(track.Id)" class="track-item">

            @Html.Partial("_imageContent_Reco", track)

            <div class="title-artist">
                <div class="title">
                    <a href="javascript:void(0);" onclick="javascript:select('@track.Id',
                            '@HttpUtility.JavaScriptStringEncode(track.Name)',
                            '@track.Artists[0].Id',
                            '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)',
                            true,
                            false);"
                       title="@track.Name" alt="@track.Name">
                        @track.Name
                    </a>

                </div>
                <div class="title">
                    @{string artists = string.Join(",", track.Artists.Select(a => a.Name));}
                    <a href="javascript:void(0);" onclick="javascript:select('@track.Id',
                            '@HttpUtility.JavaScriptStringEncode(track.Name)',
                            '@track.Artists[0].Id',
                            '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)',
                            true,
                            false);" title="@artists" alt="@artists">
                        @artists
                    </a>
                </div>

            </div>
        </li>
        }
    </ul>
}

paradify.net/pcore/pcore/pcore.web/Views/Shared/_SavedTracks.cshtml
@using SpotifyAPI.Web.Models
@using System.Web
@model Paging<SavedTrack>

@if (Model != null && Model.Items != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Artist</th>
                <th scope="col">Album</th>
                <th scope="col">Saved At</th>
                <th scope="col">Time</th>
            </tr>
        </thead>
        <tbody>

            @foreach (SavedTrack saved in Model.Items)
            {
                FullTrack track = saved.Track;
                <tr>
                    <td scope="row" style="width:47px;">
                        @if (@track.PreviewUrl != null && @track.PreviewUrl.Length > 0)
                        {
                            <div class="number-playback-pic" playback="@track.PreviewUrl" trackName="@HttpUtility.JavaScriptStringEncode(track.Name)">
                                <span class="player">
                                    <span class="play-pause"></span>
                                </span>
                                @if (track.Album.Images.Count > 0)
                                {
                                    <img class="track-image" src="@track.Album.Images[0].Url" preview-url="@track.PreviewUrl" />
                                }
                                else
                                {
                                    <img class="track-image" src="~/src/web/images/head-logo.png" preview-url="@track.PreviewUrl" />
                                }
                            </div>
                        }
                    </td>
                    <td style="width:54px;">
                        <button type="button" class="btn btn-success" onclick="javascript:select('@track.Id', '@HttpUtility.JavaScriptStringEncode(track.Name)', '@track.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)', false, false, true);"> + </button>

                    </td>
                    <td><span class="trackName">@Html.RouteLink(track.Name, "Search", new { q = track.Name }, new { title = track.Name })</span></td>
                    <td><span class="artistName">@string.Join(" - ", track.Artists.Select(a => a.Name))</span></td>
                    <td><span class="artistName">@track.Album.Name</span></td>
                    <td><span>@saved.AddedAt</span></td>
                    <td>

                        @{
                            TimeSpan t = TimeSpan.FromMilliseconds(track.DurationMs);
                            string time = string.Format("{0:D2}:{1:D2}",
                            t.Minutes,
                            t.Seconds
                            );
                        }
                        @time

                    </td>
                </tr>

            }




        </tbody>
    </table>
}

paradify.net/pcore/pcore/pcore.web/Views/Shared/_SavedTracksShort.cshtml
@using SpotifyAPI.Web.Models
@using System.Web
@model Paging<SavedTrack>

@if (Model != null && Model.Items != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"></th>
                <th scope="col">Title - Artist</th>
            </tr>
        </thead>
        <tbody>

            @foreach (SavedTrack saved in Model.Items)
            {
                FullTrack track = saved.Track;
                <tr>
                    <td scope="row" style="width:47px;">
                        <div class="number-playback-pic" playback="@track.PreviewUrl" trackName="@HttpUtility.JavaScriptStringEncode(track.Name)">
                            <span class="player">
                                <span class="play-pause"></span>
                            </span>

                            <img class="track-image" src="~/src/web/images/head-logo.png" preview-url="@track.PreviewUrl" />
                        </div>
                    </td>
                    <td style="width:54px;">
                        <button type="button" class="btn btn-success" onclick="javascript:select('@track.Id', '@HttpUtility.JavaScriptStringEncode(track.Name)', '@track.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(track.Artists[0].Name)', false, false, false, true);"> + </button>
                    </td>
                    <td>
                        @{
                            var artistNames = string.Join(" - ", track.Artists.Select(a => a.Name));
                            var trackNameArtistNames = string.Format("{0} - {1}", track.Name, artistNames);
                        }
                        <span class="trackName">@Html.RouteLink(track.Name, "Search", new { q = trackNameArtistNames }, new { title = trackNameArtistNames })</span>
                        <span class="artistName">@track.Artists.First().Name</span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

paradify.net/pcore/pcore/pcore.web/Views/Shared/_ScriptsStyles.cshtml
@{
    const string version = "21";
}
<script src="~/src/web/js/jquery-3.3.1.min.js?v=@(version)"></script>
<script src="~/src/web/js/bootstrap.min.js?v=@(version)"></script>
<script src="~/src/web/js/bootstrap-notify.min.js?v=@(version)"></script>
<script src="~/src/web/js/bootstrapCustom.js?v=@(version)"></script>
<script src="~/src/web/js/playback.js?v=@(version)"></script>
<script src="~/src/web/js/ga-track.js?v=@(version)"></script>
<link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
<link rel='stylesheet' href='~/src/web/cssChrome/bootstrap.min.css?v=@(version)' type='text/css' />
<link rel='stylesheet' href='~/src/web/cssChrome/bootstrapCustom.css?v=@(version)' type='text/css' />
<link rel='stylesheet' href='~/src/web/cssChrome/bootstrapCustom-reco.css?v=@(version)' type='text/css' />
<link rel='stylesheet' href='~/src/web/cssChrome/searchresult.css?v=@(version)' type='text/css' />
<link rel='stylesheet' href='~/src/web/cssChrome/animate.css?v=@(version)' type='text/css' />
<link rel='stylesheet' href='~/src/web/cssChrome/playback.css?v=@(version)' type='text/css' />
<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/bocdilfmhiggklhdifohjfghbdncgele">
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-3218083-16"></script>
<script>window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-3218083-16');</script>
<script>populateBottom();</script>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_imageContent.cshtml
@using SpotifyAPI.Web.Models
@using System.Web
@model FullTrack
<div class="image number-playback-pic" playback="@Model.PreviewUrl" trackName="@HttpUtility.JavaScriptStringEncode(Model.Name)">
    @if (Model.Album.Images.Count > 0)
    {
        <img class="track-image" preview-url="@Model.PreviewUrl"
             src="@Model.Album.Images[0].Url" style="width:100%; border-radius: 4px;vertical-align: middle; border:0;" />
    }
    else
    {
        <img class="track-image" src="~/src/web/images/head-logo.png" preview-url="@Model.PreviewUrl" />
    }
    <div class="track-item-overlay">
        <div class="center">
            <a href="javascript:void(0);">
                <i class="play-pause fas fa-play"></i>
            </a>
        </div>
        <div class="bottom">
            <a class="recommend" title="Recommend more like this" href="javascript:void(0);" onclick="javascript:recommend('@Model.Id', '@HttpUtility.JavaScriptStringEncode(Model.Name)', '@Model.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(Model.Artists[0].Name)');">
                <i>R</i>
            </a>
            <a class="add" href="javascript:void(0);" onclick="javascript:select('@Model.Id', '@HttpUtility.JavaScriptStringEncode(Model.Name)', '@Model.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(Model.Artists[0].Name)', true, false);">
                <i class="fas fa-plus-circle"></i>
            </a>
        </div>
    </div>
</div>

paradify.net/pcore/pcore/pcore.web/Views/Shared/_imageContent_Reco.cshtml
@using SpotifyAPI.Web.Models
@using System.Web
@model FullTrack
<div class="image number-playback-pic" playback="@Model.PreviewUrl" trackName="@HttpUtility.JavaScriptStringEncode(Model.Name)">
    @if (Model.Album.Images.Count > 0)
    {
        <img class="track-image" preview-url="@Model.PreviewUrl"
             src="@Model.Album.Images[0].Url" style="width:100%; border-radius: 4px;vertical-align: middle; border:0;" />
    }
    else
    {
        <img class="track-image" src="~/src/web/images/head-logo.png" preview-url="@Model.PreviewUrl" />
    }
    <div class="track-item-overlay">
        <div class="center">
            <a href="javascript:void(0);">
                <i class="play-pause fas fa-play"></i>
            </a>
        </div>
        <div class="bottom">
            <a class="recommend" title="Recommend more like this" href="javascript:void(0);" onclick="javascript:recommend('@Model.Id', '@HttpUtility.JavaScriptStringEncode(Model.Name)', '@Model.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(Model.Artists[0].Name)');">
                <i>R</i>
            </a>
            <a href="javascript:void(0);" onclick="javascript:select('@Model.Id', '@HttpUtility.JavaScriptStringEncode(Model.Name)', '@Model.Artists[0].Id', '@HttpUtility.JavaScriptStringEncode(Model.Artists[0].Name)', true, false);" ">
                <i class="fas fa-plus-circle"></i>
            </a>
        </div>
    </div>
</div>